FROM node:22.11.0

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile --ignore-scripts

COPY . .

RUN yarn build

EXPOSE $URL_SHORTENER_PORT

CMD [ "yarn", "start", "url-shortener" ]
